### ISSUE TITLE
Regarding the results of Table 4 in the paper

### ISSUE THREAD

**Issue by isCopyman** [dongbeank/CATS#1]
Is it reproduced using the Time series library?

**Comment by dongbeank** [comment]
Yes, it is reproduced using the Time series library. However, I modified some parameter settings to match the original paper, as they were different from the GitHub code.

**Comment by dongbeank** [comment]
Yes, it is reproduced using the Time series library. However, I modified some parameter settings to match the original paper, as they were different from the GitHub code.
