### ISSUE TITLE
exp_main.py typo

### ISSUE THREAD

**Issue by Simon-Beck12** [dongbeank/CATS#2]
in def predict, 
pred = test_data
trues = test_data,
inputx = test_data 
all should be changed to pred_data right?

**Comment by dongbeank** [comment]
Yes, it is. Those variables should all be using `pred_data` instead of `test_data`.
Please let me know if you encounter any other issues.

**Comment by Simon-Beck12** [comment]
such a concise code and great paper. i'm doing jane street kaggle project with this model. i will let you know soon

**Comment by dongbeank** [comment]
Thank you for your kind feedback :)
